### ISSUE TITLE
Duplicate to Another Course - grade category is "lost"

### ISSUE THREAD

**Issue by JosephKennedy4** [Syxton/moodle-block_massaction#82] opened 2023-09-05 20:05 UTC
When an item, or items, are selected, and "Duplicated to another course" is chosen, the items' Grade settings do not fully duplicate.  In particular, the category is not preserved, even when the target course has a category named the same as the category in the source course.

**Comment by Syxton** [comment] 2024-01-10 15:16
@JosephKennedy4 I believe that this will require a large UI change to handle with Mass Actions.  I don't believe that creation of a grade category or a "match of grade title" is something that would be expected for all duplication actions, so it would require another screen to manually select grade categories for each item on duplication.  The block should be considered as working much like Moodle Imports.  It is grabbing parts of another course, but it isn't a backup/restore exact copy.  I am leaning toward a "not a bug / will not fix" resolution unfortunately.  @PhMemmel thoughts?

**Comment by JosephKennedy4** [comment] 2024-01-10 15:31
“not a bug / will not fix” seems to be the most appropriate categorization.  If it was a “simple tweak,” I would advocate for it even though it might not philosophically align with the module, but certainly should not be considered.

**Comment by PhMemmel** [comment] 2024-01-10 15:43
Completely agree 👍

**Comment by Syxton** [comment] 2024-01-10 16:11
Closing as not a bug.

**Closed by Syxton** 2024-01-10 16:11 UTC
