### ISSUE TITLE
Improvement: Admins can duplicate in all courses

### ISSUE THREAD

**Issue by stdoma** [Syxton/moodle-block_massaction#116] opened 2024-03-14 10:47 UTC
Hello!
Currently you can only duplicate objects in courses in which you are enrolled.
In general, this is fine.
For administrators, it would be good if they could duplicate to all courses in the system by default.
Otherwise you first have to login as a specific person and then log back into your normal profile once you have finished your work.

**Comment by PhMemmel** [comment] 2024-03-14 12:04
I feel like this is a duplicate of https://github.com/Syxton/moodle-block_massaction/issues/104? See solution there :)

**Closed** 2024-03-14 12:18 UTC
